apiVersion: apps/v1
kind: Deployment
metadata:
  name: cse-project
spec:
  selector:
    matchLabels:
      run: cse-project
  replicas: 2
  template:
    metadata:
      labels:
        run: cse-project
    spec:
      containers:
        - name: cse-project
          image: ltjaasks/cse-project:latest
          ports:
            - containerPort: 8080
              protocol: TCP
